services:
  student_success_predictor:
    image: billwan96/dsci522-student_success_prediction:4bd86df
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
